# Generated by Django 5.1.2 on 2024-11-24 01:08

from django.db import migrations
from django.db.models import TextField


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=TextField(),
        ),
    ]
