# Generated by Django 5.1.2 on 2024-11-24 18:21

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpost_categories_blogpost_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
