# Generated by Django 5.1.4 on 2024-12-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
