# Generated by Django 5.1.4 on 2024-12-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('normal', 'normal'), ('urgent', 'urgent')], default='normal', max_length=65),
        ),
    ]
