# Generated by Django 5.1.4 on 2024-12-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_contact_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
