on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.paulmbui.co.ke
        username: ${{ secrets.ftp_usernane }}
        password: ${{ secrets.ftp_password }}
        server-dir: /djangoblog.paulmbui.co.ke/
